repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: local
    hooks:
      - id: ecb-check
        name: ecb check (out/csv)
        language: system
        entry: python tools/precommit_check.py
        pass_filenames: false
        always_run: true
