global:
  outdir: ./out

step1:
  eano_wide: ./data/EANO_wide.csv         # ← nastav svou skutečnou cestu
  eand_wide: ./data/EAND_wide.csv         # ← nastav svou skutečnou cestu
  wide_sep: auto                          # nebo ',', ';' podle souboru
  units: kwh

step2:
  eano_long_csv: ./out/csv/eano_long.csv
  eand_long_csv: ./out/csv/eand_long.csv
  pair_freq: H

step3:
  eano_after_pv_csv: ./out/csv/eano_after_pv.csv
  eand_after_pv_csv: ./out/csv/eand_after_pv.csv
  local_selfcons_csv: ./out/csv/local_selfcons.csv
  price_commodity_mwh: 2200
  price_distribution_mwh: 1800
  price_feed_in_mwh: 1200
  mode: hybrid
  max_recipients: 5

step4a:
  eano_after_pv_csv: ./out/csv/eano_after_pv.csv
  eand_after_pv_csv: ./out/csv/eand_after_pv.csv
  cap_kwh_per_kwp: 1.0
  eta_c: 0.95
  eta_d: 0.95

step4b-econ:
  csv_subdir: csv
  price_commodity_mwh: 2200
  price_distribution_mwh: 1800
  price_feed_in_mwh: 1200
  project_years: 15
  discount_rate: 0.05
  local_price_per_kwh: 11000
  local_fixed_cost: 0
  central_price_per_kwh: 9000
  central_fixed_cost: 0

step5a:
  eano_after_pv_csv: ./out/csv/eano_after_pv.csv
  eand_after_pv_csv: ./out/csv/eand_after_pv.csv
  central_site: CENTRAL
  cap_kwh: 200
  eta_c: 0.95
  eta_d: 0.95

step5:
  by_hour_csv: ./out/csv/by_hour_after.csv
  kwp_csv: ./out/csv/kwp_by_site.csv
  eta_c: 0.95
  eta_d: 0.95
  cap_kwh_list: "50,100,200"

step6:
  scenarios: "s1,s2,s3,s4a,s4b"
